### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED

### ISSUE THREAD

**Issue by ghost** [MEMEXProject/MEMEX-KG#1]
I get this error when I run the following:

`python main.py  --mode 7 --lang "en" --overwrite_embedding True`

Full error log:

```
2142
  3%|███▊                                                                                                                                       | 59/2142 [02:19<1:06:06,  1.90s/it]/home/muhammadmehdi/anaconda3/envs/memex/lib/python3.7/site-packages/wikipedia/wikipedia.py:389: GuessedAtParserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 389 of the file /home/muhammadmehdi/anaconda3/envs/memex/lib/python3.7/site-packages/wikipedia/wikipedia.py. To get rid of this warning, pass the additional argument 'features="html.parser"' to the BeautifulSoup constructor.

  lis = BeautifulSoup(html).find_all('li')
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2142/2142 [1:21:35<00:00,  2.29s/it]
Downloading: "https://download.pytorch.org/models/resnet18-5c106cde.pth" to /home/muhammadmehdi/.cache/torch/hub/checkpoints/resnet18-5c106cde.pth
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 44.7M/44.7M [00:20<00:00, 2.28MB/s]
  0%|                                                                                                                                                      | 0/1214 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 271, in <module>
    db_desc.update_visual_desc_emb(nodes)
  File "/home/muhammadmehdi/PycharmProjects/memex/MEMEX-KG/db/db_desc.py", line 185, in update_visual_desc_emb
    emb = get_visal_embedding(model,I)
  File "/home/muhammadmehdi/PycharmProjects/memex/MEMEX-KG/db/models.py", line 120, in get_visal_embedding
    d = model(image).view(-1).cpu().detach()
  File "/home/muhammadmehdi/anaconda3/envs/memex/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/muhammadmehdi/anaconda3/envs/memex/lib/python3.7/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/muhammadmehdi/anaconda3/envs/memex/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/muhammadmehdi/anaconda3/envs/memex/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 399, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/muhammadmehdi/anaconda3/envs/memex/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 396, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED
CRITICAL: Exiting due to uncaught exception <class 'RuntimeError'>
```
My cuda version is 11.2, Ubuntu 20.04, torch version 0.4.1, and torchvision version 0.9.0, GTX 1650 (laptop edition)

**Comment by ghost** [comment]
I fixed the problem by using torch==1.9.0 and torchvision==0.10.0
